# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019
SHELL ["powershell","-NoLogo","-NonInteractive","-Command"]
WORKDIR C:\app

COPY main.ps1 C:\app\main.ps1

# Cho phép bind http://+:8080/ khi không chạy quyền admin
RUN netsh http add urlacl url=http://+:8080/ user=Everyone

EXPOSE 8080
ENTRYPOINT ["powershell.exe","-File","C:\\app\\main.ps1"]