# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell","-NoLogo","-NonInteractive","-Command"]
WORKDIR C:\app

# Copy ứng dụng
COPY main.ps1 C:\app\main.ps1

# Cho phép bind http://+:8080/ khi không chạy quyền admin
RUN netsh http add urlacl url=http://+:8080/ user=Everyone

EXPOSE 8080

# Khởi chạy script (bypass execution policy để tránh bị chặn)
ENTRYPOINT ["powershell.exe","-ExecutionPolicy","Bypass","-File","C:\\app\\main.ps1"]
