# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell","-NoLogo","-NonInteractive","-Command"]
WORKDIR C:\app

# copy app
COPY main.ps1 C:\app\main.ps1

# cho phép bind http://+:8080/ khi không chạy admin
RUN netsh http add urlacl url=http://+:8080/ user=Everyone

EXPOSE 8080

# chạy script (bypass execution policy)
ENTRYPOINT ["powershell.exe","-ExecutionPolicy","Bypass","-File","C:\\app\\main.ps1"]
